/*
public class Exc4 {
    public static void main(String[] args){
        try {
            int a = 0;
            int b = 42 / a;
        } catch (Exception e){
            System.out.println("Общий перехват Exception");
        } catch (ArithmeticException e){    //этот exception never will done
            System.out.println("Arifmetic Exception");
        }
    }
}
*/